declare module 'react-native-textarea'
declare module 'react-native-material-menu'
declare module '@types/react-native-camera-roll-picker'
declare module 'react-native-camera-roll-picker'
declare module '@remobile/react-native-camera-roll-picker'
declare module '@env'