export const screenNames = {
  Home: "Home",
  Search: "Search",
  Add: "Add",
  Favorites: "Favorites",
  Profile: "Profile",
  Chat: "Chat",
  ChatList: "ChatList",
  LogIn: "LogIn",
  SignUpWithEmail: "SignUpWithEmail",
  SignUpWithEmailStep2: "SignUpWithEmailStep2",
  PublicModelProfileScreen: "PublicModelProfileScreen",
  TermsCondition: "TermsCondition",
  UpdateInfo: "UpdateInfo",
  Setting: "Setting",
  ChangePassword: "ChangePassword",
  AddPhotoStep2: "AddPhotoStep2",
  AddPhotoStep3: "AddPhotoStep3",
  Billing: "Billing",
  ModelPrice: "ModelPrice",
  DeleteAccount: "DeleteAccount",
}
