export const screenNames = {
  Home: "Home",
  Search: "Search",
  Add: "Add",
  Favorites: "Favorites",
  Profile: "Profile",
  Chat: "Chat",
  ChatList: "ChatList",
  LogIn: "LogIn",
  SignUpWithEmail: "SignUpWithEmail",
  SignUpWithEmailStep2: "SignUpWithEmailStep2",
  PublicModelProfileScreen: "PublicModelProfileScreen",
  TermsCondition: "TermsCondition",
  UpdateInfo: "UpdateInfo",
  Setting: "Setting",
  ChangePassword: "ChangePassword",
  AddMediaStep2: "AddMediaStep2",
  AddMediaStep3: "AddMediaStep3",
  Billing: "Billing",
  ModelPrice: "ModelPrice",
  DeleteAccount: "DeleteAccount",
  ResetPassword: "ResetPassword",
  ResetPasswordStep2: "ResetPasswordStep2",
  ResetPasswordStep3: "ResetPasswordStep3",
}
